import numpy as np

def unbroadcast(grad: np.ndarray, shape: tuple) -> np.ndarray:
    # Remove redundant dimensions generated by broadcast
    # For example, (1, 1, 4, 5) -> (4, 5)
    while grad.ndim > len(shape):
        grad = grad.sum(axis=0)

    # Sum dimension where shape is 1
    for i, dim in enumerate(shape):
        if dim == 1:
            grad = grad.sum(axis=i, keepdims=True)

    return grad

# (2, 2, 2) + (2, 2) -> (2, 2, 2)
# Expand:
# (2, 2) -> (1, 2, 2) --[copy]-> (2, 2, 2)
# Unbroadcast:
# grad(2, 2, 2), shape(2, 2)
# 
