import numpy as np

def unbroadcast(grad: np.ndarray, shape: tuple) -> np.ndarray:
    # Remove redundant dimensions generated by broadcast
    # For example, (1, 1, 4, 5) -> (4, 5)
    while grad.ndim > len(shape):
        grad = grad.sum(axis=0)

    # Sum dimension where shape is 1
    for i, dim in enumerate(shape):
        if dim == 1:
            grad = grad.sum(axis=i, keepdims=True)

    return grad